# Generated by Django 6.0.6 on 2026-07-06 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_profile_height_profile_objective_profile_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.CharField(choices=[('M', 'Mensal'), ('T', 'Trimestral'), ('S', 'Semestral')], default='M', max_length=1)),
                ('status', models.BooleanField(default=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='accounts.profile')),
            ],
        ),
    ]
