# Generated by Django 6.0.6 on 2026-07-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('description', models.TextField()),
                ('muscle_group', models.CharField(choices=[('PE', 'Peito'), ('C', 'Costas'), ('O', 'Ombros'), ('B', 'Braços'), ('P', 'Pernas'), ('G', 'Gluteos'), ('A', 'Abdômen')], max_length=12)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='muscle_group/')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
