# Generated by Django 6.0.6 on 2026-07-06 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='exercise/'),
        ),
    ]
